version: 2.1

orbs:
  node: circleci/node@5.0.2
  coveralls: coveralls/coveralls@2.2.5

jobs:
  build_and_test: 
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test:e2e
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  coveralls:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run coverage
          command: npm run test:cov
      - coveralls/upload:
          coverage_file: coverage/lcov.info

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - coveralls:
          requires:
            - build_and_test